name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag-version:
        description: Tag version of the build
        required: true
        default: latest
        type: string
        
env:
  VERSION: ${{ inputs.tag-version != '' && inputs.tag-version || 'latest' }}
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        tags: skyscanner:latest
        outputs: type=docker,dest=/tmp/skyscanner.tar
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: skyscanner:latest
        path: /tmp/skyscanner.tar
