name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag-version:
        description: Tag version of the build
        required: true
        default: latest
        type: string
        
env:
  VERSION: ${{ inputs.tag-version != '' && inputs.tag-version || 'latest' }}
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag skyscanner:$VERSION

    - name: Generate tar file
      run: docker save --output skyscanner.tar skyscanner:$VERSION
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: skyscanner:$VERSION
        path: skyscanner.tar
