name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag-version:
        description: Tag version of the build
        required: true
        default: v1.0.0
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag skyscanner:$VERSION
      env:
        VERSION: ${{ inputs.tag-version }}
